author: "Robbert Brandsma & Joannis Orlandos"
module: MongoKitten
readme: README.md
github_url: https://github.com/PlanTeam/MongoKitten
swift_version: 2.2
xcodebuild_arguments:
  - "-scheme"
  - "MongoKitten"
dash_url: http://planteam.github.io/MongoKitten/MongoKitten.xml
